Added Advanced Search using Groups
ubisoft/NGitLab pull request #129
Opened 2021-11-09 08:01 UTC by weissm

The  [Group API](https://docs.gitlab.com/ee/api/search.html#scope-projects-1) specifies the following format:

> `curl --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/groups/3/search?scope=projects&search=flight"`.

This group selection is supported by introducing the `groupID `parameter to the `ProjectQuery` scope.

2021-11-10 12:38 UTC, louis-z commented
Thanks for the contribution, @weissm. There are, however, a few things that need to be fixed:
- Since the route is `groups/3/search`, changes should be made to `GroupsClient` rather than `ProjectClient`.
- There are already a few search options offered by `GroupsClient`, e.g. [to search for a group](https://docs.gitlab.com/ee/api/groups.html#search-for-group) and [to list a group’s projects](https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects). We need to make it clear to the user what this new search feature offers.
- Maybe instead of using an existing Query type we should introduce a new `SearchParameters` type? At a glance, it seems that [all search types listed in the doc](https://docs.gitlab.com/ee/api/search.html) use the same set of parameters.
- Tests and mocks should be added as well

2021-11-15 17:33 UTC, meziantou requested changes
LGTM after changing the property name

2021-11-15 17:33 UTC, meziantou commented on NGitLab/Models/ProjectQuery.cs
> +        public string GroupID;
```suggestion
        public string GroupId;
```

2021-11-15 17:33 UTC, meziantou commented on NGitLab/Impl/ProjectClient.cs
> +            if (query.GroupID != string.Empty)
```suggestion
            if (!string.IsNullOrEmpty(query.GroupId))
```

2021-11-18 21:04 UTC, weissm commented
Incorporated comments in https://github.com/ubisoft/NGitLab/pull/131

2021-11-18 21:04 UTC, closed without merging