Add protected branches client
ubisoft/NGitLab pull request #24
Opened 2021-06-17 10:07 UTC by Codex04

- Protect a branch  
- Unprotect a branch  
- Get a single protected branch  
- Get a list of protected branches  

GitLab Protected Branches API Documentation: https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches

2021-06-17 13:46 UTC, meziantou requested changes

2021-06-17 13:46 UTC, meziantou commented on NGitLab/Models/AccessLevel.cs
> +        NoAccess = 0,
You should move it to the first position

2021-06-17 13:46 UTC, meziantou commented on NGitLab/Models/AccessLevel.cs
> +        NoAccess = 0,
[According to the documentation](https://docs.gitlab.com/ee/api/protected_branches.html) there is an `Admin = 60` mode

2021-06-17 13:46 UTC, meziantou commented on NGitLab/Impl/ProtectedBranchesClient.cs
> +            => _api.Delete().Execute($"{_protectedBranchesUrl}/{branchName}");
```suggestion
            => _api.Delete().Execute($"{_protectedBranchesUrl}/{Uri.EscapeDataString(branchName)}");
```

2021-06-17 13:46 UTC, meziantou commented on NGitLab/Impl/ProtectedBranchesClient.cs
> +            => _api.Get().To<ProtectedBranch>($"{_protectedBranchesUrl}/{branchName}");
```suggestion
            => _api.Get().To<ProtectedBranch>($"{_protectedBranchesUrl}/{Uri.EscapeDataString(branchName)}");
```

2021-06-17 13:46 UTC, meziantou commented on NGitLab/Impl/ProtectedBranchesClient.cs
> +            var searchParameter = string.IsNullOrWhiteSpace(search) ? string.Empty : $"/search={search}";
The `search` parameter is in the query string, not the path. Also the value must be escaped.
You should use  `Utils.AddParameter` to set it.

2021-06-17 14:54 UTC, meziantou approved these changes

2021-06-17 15:06 UTC, louis-z requested changes

2021-06-17 15:06 UTC, louis-z commented on NGitLab/IProtectedBranchesClient.cs
> +    public interface IProtectedBranchesClient
Please rename to `IProtectedBranchClient`. As per most other client interfaces, it should be named with a singular noun followed by `Client`.

Rename derived types and methods too accordingly.

2021-06-17 15:06 UTC, louis-z commented on NGitLab/Models/ProtectedBranch.cs
> +        [DataMember(Name = "merge_acess_levels")]
```suggestion
        [DataMember(Name = "merge_access_levels")]
```

2021-06-17 15:09 UTC, meziantou commented on NGitLab/Models/ProtectedBranch.cs
> +        [DataMember(Name = "merge_acess_levels")]
You should add a test to ensure the property names are ok

2021-06-18 11:25 UTC, louis-z requested changes

2021-06-18 11:25 UTC, louis-z commented on NGitLab.Mock/Clients/GitLabClient.cs
> +        public IProtectedBranchClient GetProtectedBranchesClient(int projectId)
```suggestion
        public IProtectedBranchClient GetProtectedBranchClient(int projectId)
```

2021-06-18 11:25 UTC, louis-z commented on NGitLab/GitLabClient.cs
> +        public IProtectedBranchClient GetProtectedBranchesClient(int projectId)
```suggestion
        public IProtectedBranchClient GetProtectedBranchClient(int projectId)
```

2021-06-18 11:25 UTC, louis-z commented on NGitLab/IGitLabClient.cs
> +        IProtectedBranchClient GetProtectedBranchesClient(int projectId);
```suggestion
        IProtectedBranchClient GetProtectedBranchClient(int projectId);
```

2021-06-18 11:25 UTC, louis-z commented on NGitLab/IProtectedBranchClient.cs
> +        ProtectedBranch GetProtectedBranches(string search);
Won't that call return an array of `ProtectedBranch`es?

2021-06-18 12:04 UTC, Codex04 commented on NGitLab/IProtectedBranchClient.cs
> +        ProtectedBranch GetProtectedBranches(string search);
Yep that's true. I changed it

2021-06-18 12:13 UTC, louis-z approved these changes

2021-06-18 13:09 UTC, meziantou commented on NGitLab.Tests/ProtectedBranchTests.cs
> +            var expectedBranchProtectJson = Regex.Replace(
Not sure why you use a regex. You can use string.replace or `SimpleJson.Serialize(SimpleJson.Deserialize(...))`

2021-06-21 15:10 UTC, merged