Implement milestone client for mocks
ubisoft/NGitLab pull request #42
Opened 2021-07-07 16:05 UTC by LePtitDev

2021-07-07 18:09 UTC, meziantou requested changes

2021-07-07 18:09 UTC, meziantou commented on NGitLab.Mock/Clients/MilestoneClient.cs
> +                var project = FindProject(_projectId) ?? throw new InvalidOperationException($"Cannot find project with ID {_projectId}");
Most of the comments from https://github.com/ubisoft/NGitLab/pull/41 applies here too :)

2021-07-08 12:57 UTC, meziantou commented on NGitLab.Mock/Clients/MilestoneClient.cs
> +                    DueDate = string.IsNullOrEmpty(milestone.DueDate) ? DateTimeOffset.Now : DateTimeOffset.Parse(milestone.DueDate),
```suggestion
                    DueDate = string.IsNullOrEmpty(milestone.DueDate) ? DateTimeOffset.UtcNow : DateTimeOffset.Parse(milestone.DueDate),
```

2021-07-08 12:57 UTC, meziantou commented on NGitLab.Mock/Clients/MilestoneClient.cs
> +                    StartDate = string.IsNullOrEmpty(milestone.StartDate) ? DateTimeOffset.Now : DateTimeOffset.Parse(milestone.StartDate),
```suggestion
                    StartDate = string.IsNullOrEmpty(milestone.StartDate) ? DateTimeOffset.UtcNow : DateTimeOffset.Parse(milestone.StartDate),
```

2021-07-08 12:57 UTC, meziantou commented on NGitLab.Mock/Clients/MilestoneClient.cs
> +                    ms.StartDate = DateTimeOffset.Parse(milestone.StartDate);
You use use an overload that accepts `CultureInfo.InvariantCulture`

2021-07-08 12:57 UTC, meziantou commented on NGitLab.Mock/Clients/MilestoneClient.cs
> +                    ms.DueDate = DateTimeOffset.Parse(milestone.DueDate);
You use use an overload that accepts `CultureInfo.InvariantCulture`

2021-07-08 17:45 UTC, meziantou approved these changes

2021-07-09 13:39 UTC, louis-z requested changes

2021-07-09 13:39 UTC, louis-z commented on NGitLab.Mock.Tests/MilestonesMockTests.cs
> +        public void Test_milestones_from_project_can_be_found()
```suggestion
        public void Test_milestones_can_be_found_from_project()
```

2021-07-13 13:14 UTC, louis-z approved these changes

2021-07-13 13:27 UTC, merged