Extend CommitStatus model
ubisoft/NGitLab pull request #450
Opened 2023-05-24 10:09 UTC by partemyeva

https://docs.gitlab.com/15.11/ee/api/commits.html#list-the-statuses-of-a-commit

curl --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/projects/17/repository/commits/18f3e63d05582537db6d183d9d557be09e1f90c8/statuses"

2023-05-26 15:31 UTC, jairbubbles commented
Thanks for the contribution @partemyeva, we'll look into it in the coming days. Maintainers are currently in vacation.

2023-05-30 16:58 UTC, louis-z requested changes

2023-05-30 16:58 UTC, louis-z commented on NGitLab/Models/Commit.cs
> +        public Pipeline Pipeline;
Please rename this as `LastPipeline`.

2023-06-02 11:42 UTC, louis-z approved these changes

2023-06-02 19:21 UTC, merged