Add support for Lint endpoints
ubisoft/NGitLab pull request #460
Opened 2023-06-05 20:02 UTC by mchanyeechoy

Add endpoints from https://docs.gitlab.com/ee/api/lint.html

2023-06-06 12:04 UTC, louis-z requested changes

2023-06-06 12:04 UTC, louis-z commented on NGitLab/Impl/LintClient.cs
> +        public Task<LintCI> LintGitLabCIYamlAsync(string projectId, string yamlContent, LintCIOptions options, CancellationToken cancellationToken = default)
I think the methods can have clearer names.

In [the doc](https://docs.gitlab.com/ee/api/lint.html#validate-a-ci-yaml-configuration-with-a-namespace), this is described as `Validate a CI YAML configuration with a namespace`, but to make it even clearer that we're passing in YAML content:

```suggestion
        public Task<LintCI> ValidateCIYamlContentAsync(string projectId, string yamlContent, LintCIOptions options, CancellationToken cancellationToken = default)
```

2023-06-06 12:04 UTC, louis-z commented on NGitLab/Impl/LintClient.cs
> +        public Task<LintCI> LintProjectGitLabCIYamlAsync(string projectId, LintCIOptions options, CancellationToken cancellationToken = default)
The [doc](https://docs.gitlab.com/ee/api/lint.html#validate-a-projects-ci-configuration) calls this `Validate a project’s CI configuration`

```suggestion
        public Task<LintCI> ValidateProjectCIConfigurationlAsync(string projectId, LintCIOptions options, CancellationToken cancellationToken = default)
```

2023-06-06 12:04 UTC, louis-z commented on NGitLab/Impl/LintClient.cs
> +            url = Utils.AddParameter(url, "content", yamlContent);
According to the request example in the doc, `yamlContent` is supposed to be passed in as POST data, not as query parameter:

> curl --header "Content-Type: application/json" "https://gitlab.example.com/api/v4/projects/:id/ci/lint" --data '{"content": "{ \"image\": \"ruby:2.6\", \"services\": [\"postgres\"], \"before_script\": [\"bundle install\", \"bundle exec rake db:create\"], \"variables\": {\"DB_NAME\": \"postgres\"}, \"types\": [\"test\", \"deploy\", \"notify\"], \"rspec\": { \"script\": \"rake spec\", \"tags\": [\"ruby\", \"postgres\"], \"only\": [\"branches\"]}}"}'

It's strange that tests are passing... 🤔

2023-06-06 12:04 UTC, louis-z commented on NGitLab/Models/LintCI.cs
> +        [JsonPropertyName("id")]
```suggestion
        [JsonPropertyName("merged_yaml")]
```

2023-06-06 12:04 UTC, louis-z commented on NGitLab/Models/LintCIOptions.cs
> +        public bool DryRun { get; set; }
Since it's not a required param, can you make it nullable?

2023-06-06 12:46 UTC, mchanyeechoy commented on NGitLab/Impl/LintClient.cs
> +            url = Utils.AddParameter(url, "content", yamlContent);
Seems like they both work, but I will change it to be inline with the docs 🙂

2023-06-07 14:34 UTC, louis-z approved these changes

2023-06-07 14:35 UTC, merged