Add ability to get job artifact by Ref
ubisoft/NGitLab pull request #564
Opened 2023-11-17 09:34 UTC by shivan

see #563

2023-11-17 14:10 UTC, louis-z requested changes

2023-11-17 14:10 UTC, louis-z commented on NGitLab/Models/JobArtifactQuery.cs
> +        public string JobName;
Please define properties rather than fields.

2023-11-17 14:13 UTC, louis-z commented on NGitLab/Models/JobArtifactQuery.cs
> +    public class JobArtifactQuery
```suggestion
    public sealed class JobArtifactQuery
```

2023-11-17 14:16 UTC, shivan commented on NGitLab/Models/JobArtifactQuery.cs
> +        public string JobName;
ok

2023-11-20 14:21 UTC, shivan commented
@louis-z any further changes requested? Or all ok now?

2023-11-20 19:08 UTC, louis-z commented
> @louis-z any further changes requested? Or all ok now?

I had a quick look and it seems fine. Can you merge or rebase from the main branch? Note that there are conflicts. I'll have one more look at it tomorrow.

2023-11-21 12:59 UTC, merged