Add support for the "Update pipeline metadata" API
ubisoft/NGitLab pull request #736
Opened 2024-08-14 20:05 UTC by ap0llo

Adds method `UpdateMetadataAsync()` to `IPipelineClient` that calls the ["Update pipeline metadata" API](https://docs.gitlab.com/ee/api/pipelines.html#update-pipeline-metadata).

The REST API currently only supports setting the pipeline name but it looks like it is designed in a way that might allow setting other values in the future, so the metadata to update is passed to `UpdateMetadataAsync()` as an object rather than individual values.
This should allow adding additional data without changing the signature of the method.

Notes on testing:

- I manually verified the implementation with a test project on gitlab.com.
- I have also added an integration test but was not able to verify if it works since the feature is not supported by the version of GitLab currently used in the test container (container uses GitLab v15 but updating the pipeline metadata requries v16 as far as I can tell).

2024-08-15 11:42 UTC, louis-z requested changes
Thanks for your contribution, @ap0llo.

2024-08-15 11:42 UTC, louis-z commented on NGitLab.Mock/Clients/PipelineClient.cs
> +            // Currently, "name" is the only field that can be update dvia the "Update pipeline metadata" API
```suggestion
            // Currently, "name" is the only field that can be updated via the "Update pipeline metadata" API
```

2024-08-15 11:42 UTC, louis-z commented on NGitLab/Models/PipelineBasic.cs
> +    public string Name;
Make this a property instead.

Granted, legacy code uses public fields, but we shouldn't add any more.

2024-08-15 11:42 UTC, louis-z commented on NGitLab/Models/Pipeline.cs
> +    public string Name;
Make this a property instead.

2024-08-15 15:27 UTC, ap0llo commented
Thanks for your review!

I have incorporated your feedback

2024-08-16 11:18 UTC, louis-z approved these changes

2024-08-16 11:19 UTC, merged