Add Page property to control pagination. Add asynchronous support for GetCommits, GetCommit, and GetCommitDiff
ubisoft/NGitLab pull request #754
Opened 2024-09-09 16:24 UTC by ingshak

Added a `Page` property to control pagination, helping to avoid unnecessary data fetches.
Introduced asynchronous support for the following methods: GetCommits, GetCommit, and GetCommitDiff.

2024-09-23 12:09 UTC, louis-z requested changes

2024-09-23 12:09 UTC, louis-z commented on NGitLab.Tests/RepositoryClient/RepositoryClientTests.cs
> +        var since = DateTime.UtcNow;
Unless I'm missing something, the test here will collect no commit whatsoever. To truly test this, you should create a few (e.g. 5) commits over a small period of time, say one every 200 ms, and then list commits from the creation time of one of the middle commits.

2024-09-23 12:09 UTC, louis-z commented on NGitLab.Tests/RepositoryClient/RepositoryClientTests.cs
> +        Assert.That(lastRequestQueryString, Does.Contain($"since={expectedSinceValue}"));
This assertion has little value. What's more relevant is that we do get only the commits from `since`...

2024-09-23 12:09 UTC, louis-z commented on NGitLab.Tests/RepositoryClient/RepositoryClientTests.cs
> +        Assert.That(lastRequestQueryString, Does.Not.Contain("since="));
Again, I'm not sure this assertion is relevant... I would probably remove that test altogether.

2024-09-23 12:09 UTC, louis-z commented on NGitLab.Tests/RepositoryClient/RepositoryClientTests.cs
> +        var defaultBranch = context.Project.DefaultBranch;
Again, I would stagger the creation commits over a short period of time and validate that specifying `until` works as expected.

2024-09-23 12:09 UTC, louis-z commented on NGitLab.Tests/RepositoryClient/RepositoryClientTests.cs
> +    public async Task GetCommitsDoesntIncludeUntilWhenNotSpecifiedAsync()
Remove test?

2024-09-23 12:09 UTC, louis-z commented on NGitLab.Tests/RepositoryClient/RepositoryClientTests.cs
> +        Assert.That(queryParameters, Does.Not.Contain("page"));
I would prefer that the behavior, from a user's perspective, be tested. With a 5-commit setup and `per_page=2`  you could test what happens when `page` 
- is not set
- is < 3
- is >= 3

2024-09-23 12:09 UTC, louis-z commented on NGitLab.Tests/RepositoryClient/RepositoryClientTests.cs
> +    public async Task GetCommitsDoesntIncludePageWhenNotSpecifiedAsync()
Remove test?

2024-09-28 14:31 UTC, ingshak commented on NGitLab.Tests/RepositoryClient/RepositoryClientTests.cs
> +        var since = DateTime.UtcNow;
This function is similar to GetCommitsSince. The common code has been refactored and is now shared between both functions. Should I also update GetCommitsSince to align with these changes? Also, I agree I need to at least add a new test to ensure it is thoroughly tested.

2025-05-03 15:03 UTC, closed without merging